### ISSUE TITLE
Today is 9 April 2024

### ISSUE THREAD

**Issue by T1aNS1R** [wyang-vis/EIFNet#2]

**Comment by wyang-vis** [comment]
Sorry for not updating the code in time. I can package the source code and
send it to you by email.

T1aNS1R ***@***.***> 于2024年4月9日周二 11:35写道：

**Comment by DachunKai** [comment]
@wyang-vis Hi，could you send a copy of the code to my email （i.dachunkai@gmail.com）. Thanks.

**Comment by wyang-vis** [comment]
We have uploaded a version of the code, please contact us if you have any questions!

**Comment by wyang-vis** [comment]
We have uploaded a version of the code, please contact us if you have any questions!
