### ISSUE TITLE
question about dataset

### ISSUE THREAD

**Issue by xiaozibuqi** [wyang-vis/EIFNet#3]
I want to train this network with my dataset, what should I change the dataset file format to?

**Comment by wyang-vis** [comment]
Thank you for your attention. You can prepare your Train & Test data with:
- blur
   - GOPR0384_11_00
     - 0000.png
- event
   - GOPR0384_11_00
     - 0000.npz
- gt
   - GOPR0384_11_00
     - 0000.png
